name: Suspicious Application Allowed Through Exploit Guard
id: 42205c73-75c8-4a63-9db1-e3782e06fda0
author: Nasreddine Bencherchali (Nextron Systems)
date: 2022-08-05
severity: high
description: Detects applications being added to the "allowed applications" list of
  exploit guard in order to bypass controlled folder settings
status: test
modified: 2023-08-17
logsource:
  category: registry_set
  product: windows
tactics:
- Defense-evasion
relevantTechniques:
- T1562
query: 'DeviceRegistryEvents

  | where RegistryKey contains "SOFTWARE\\Microsoft\\Windows Defender\\Windows Defender
  Exploit Guard\\Controlled Folder Access\\AllowedApplications" and (RegistryKey contains
  "\\Users\\Public" or RegistryKey contains "\\AppData\\Local\\Temp" or RegistryKey
  contains "\\Desktop" or RegistryKey contains "\\PerfLogs" or RegistryKey contains
  "\\Windows\\Temp")'
eventGroupingSettings:
  aggregationKind: SingleAlert
queryFrequency: P1D
queryPeriod: P1D
enabled: true
entityMappings: null
sentinelEntitiesMappings: null
triggerThreshold: 0
suppressionDuration: PT5H
suppressionEnabled: false
triggerOperator: GreaterThan
kind: Scheduled
