on:
  push:
    branches: [main]
    paths:
    - "AnalyticRules/*.yaml"
  workflow_dispatch:

permissions:
  contents: write

name: Build YAML Analytic Rules

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build YAML Analytic Rules
    steps:
    - uses: actions/checkout@v3
    - name: Convert rules to YAML
      run: |
        Install-Module SentinelARConverter -AcceptLicense -Force
        Get-ChildItem -Path 'AnalyticRules' -Filter '*.yaml' | ForEach-Object {
            Write-Output "Processing file: $($_.Name)"
            $yamlFilePath = $_.FullName.Replace('.yaml', '.json')
            if (-not (Test-Path $yamlFilePath) -or (Get-Item $yamlFilePath).LastWriteTime -lt $_.LastWriteTime) {
                Write-Host "Converting $($_.FullName) to $yamlFilePath"
                Convert-SentinelARYamlToArm -Filename $_.FullName -UseOriginalFilename
            }
        }
      shell: pwsh
    - name: Commit and push changes
      run: |
        git config --global user.name 'Khaled6120'
        git config --global user.email 'khalednaes3@gmail.com'
        git add AnalyticRules
        git commit -am "SentinelARConverter"
        git push
